services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prom-config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prom-data:/prometheus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment: 
      - TZ=Europe/Rome
    networks:
      - proxy
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped        
    security_opt:
      - no-new-privileges:true
    environment: 
      - TZ=Europe/Rome
    networks:
      - proxy

networks:
  proxy:
    external: true
