services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    group_add:
      - '104'
      - '44'  
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/video/film/:/Films:ro
      - /mnt/video/serie-tv/:/TVShows:ro
        #- /mnt/ncdata/mike/files/Musica/:/Musica:ro
        #- Audiobooks:/Audiobooks:ro
    ports: 
      - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=web, websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=production"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
