---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: HOME
background: 
  image: https://images.unsplash.com/photo-1489058535093-8f530d789c3b?ixid=M3wxMTI1OHwwfDF8cmFuZG9tfHx8fHx8fHx8MTcwODU4OTMwMXw&ixlib=rb-4.0.3&q=85&w=1920
  saturate: 0
  brightness: 50
  opacity: 50  
  blur: sm  

theme: dark
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
